### ISSUE TITLE
运行demo的时候报这个错误

### ISSUE THREAD

**Issue by relyn** [yaphone/itchat4j#31]
2017-06-21 15:59:40,926 INFO  => 获取UUID
2017-6-21 15:59:41 cn.zhouyafeng.itchat4j.utils.MyHttpClient doGet
信息: java.lang.RuntimeException: Could not generate DH keypair
2017-06-21 15:59:41,220 ERROR => Entity may not be null
java.lang.IllegalArgumentException: Entity may not be null
	at org.apache.http.util.Args.notNull(Args.java:54)
	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:305)
	at cn.zhouyafeng.itchat4j.service.impl.LoginServiceImpl.getUuid(LoginServiceImpl.java:115)
	at cn.zhouyafeng.itchat4j.controller.LoginController.login(LoginController.java:35)
	at cn.zhouyafeng.itchat4j.Wechat.<init>(Wechat.java:22)
	at cn.zhouyafeng.itchat4j.demo.demo1.MyTest.main(MyTest.java:17)

**Comment by yaphone** [comment]
JDK使用1.7以上
