### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/http/client/CookieStore

### ISSUE THREAD

**Issue by lixunhui** [yaphone/itchat4j#42]
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/client/CookieStore
	at cn.zhouyafeng.itchat4j.core.Core.<init>(Core.java:62)
	at cn.zhouyafeng.itchat4j.core.Core.getInstance(Core.java:33)
	at cn.zhouyafeng.itchat4j.controller.LoginController.<clinit>(LoginController.java:25)
	at cn.zhouyafeng.itchat4j.Wechat.<init>(Wechat.java:19)
	at cn.test.wechat.Application.main(Application.java:16)
Caused by: java.lang.ClassNotFoundException: org.apache.http.client.CookieStore
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 5 more

**Comment by sforce100** [comment]
@lixunhui 你解决了吗，我也遇到了

**Comment by vasu-kukkapalli** [comment]
@lixunhui, were you able to solve this? please provide the solution if yes since i am also facing the same issue, Thank you!
